# Generated by Django 4.2.5 on 2024-02-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
    ]
