# Generated by Django 4.2.5 on 2024-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_remove_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, default='avator.png', null=True, upload_to='ava'),
        ),
    ]
