# Generated by Django 4.2.5 on 2024-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.PositiveIntegerField(choices=[(300, 'Superuser'), (200, 'Admin'), (100, 'Consultant')], default=100, verbose_name='User Group'),
        ),
    ]
