# Generated by Django 4.2.5 on 2024-01-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_user_alternate_phone_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='writer_assigned',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='client',
            new_name='title',
        ),
    ]
