# Generated by Django 4.2.5 on 2024-02-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_project_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='title',
        ),
    ]
